name: Test de Categoría

on:
  push:
    branches: [ dev-joan-saavedra ]
  pull_request:
    branches: [ dev-joan-saavedra ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar y correr tests de Categoría
        run: ./mvnw -Dtest=*Category* test

